objects/Answer__c.object
<CustomObject>
    <description>Contains SurveyGizmo survey answer text and rating scales.</description>
    <label>Answer</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Presenter_No__c</fullName>
        <label>Presenter No.</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <recordTypes>
        <fullName>Presenter</fullName>
        <active>true</active>
        <description>Includes Job Items as a related list.</description>
        <label>Presenter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Contains survey question numbers and text.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>QU-{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Response__c.object
<CustomObject>
    <description>Records survey responses from SurveyGizmo.</description>
    <label>Response</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Section.cls
public class Section{
  public List<Question__c> questions;
  public List<Answer__c> answers;
  public List<Response__c> responses;
  public String Section;
  public String Average;
  public String SType;
  
  public Section(String cSection, List<Question__c> cquestions, List<Answer__c> canswers, Decimal caverage, String ctype, List<Response__c> cresponses){
     questions = cquestions;
     answers = canswers;
     Section = cSection;
     Average = string.valueOf(caverage.setScale(2));
     responses = cresponses;
     SType = ctype;
  }
  
  public List<Question__c> getQuestions(){
    return questions;
  }
  
  public List<Answer__c> getAnswers(){
    return answers;
  }
  
  public List<Response__c> getResponses(){
    return responses;
  }
  
  public String getSection(){
	  	String jobid=ApexPages.currentPage().getParameters().get('Id');
	  	
	  	if (Section=='Presenter 1') {
	  		Integer counter=[select count() from job_role__c where Presenter_No__c='1' AND Job__c = :jobid];
            if (counter>0){
               Job_Role__c aJobRole= [select Contact__r.name from job_role__c where Presenter_No__c='1' AND Job__c = :jobid];
               Section='Presenter 1 '+ajobrole.Contact__r.name;
            }
            else{
                Section='Presenter 1 ';
            }

	  	}
	  	if (Section=='Presenter 2') {
	        
	        Integer counter=[select count() from job_role__c where Presenter_No__c='2' AND Job__c = :jobid];
	        if (counter>0){
	           Job_Role__c aJobRole= [select Contact__r.name from job_role__c where Presenter_No__c='2' AND Job__c = :jobid];
	           Section='Presenter 2 '+ajobrole.Contact__r.name;
	        }
	        else{
				Section='Presenter 2 ';
		    }

	    }
	   if (Section=='Presenter 3') {
	        
		    Job_Role__c aJobRole= [select Contact__r.name from job_role__c where Presenter_No__c='3' AND Job__c = :jobid];
		    Section='Presenter 3 '+ajobrole.Contact__r.name; 
	    }
	    return Section;
  }
  
  public String getType(){
    return SType;
  }
  
  public String getAverage(){


  	return string.valueOf(Average);
    
  }
}