objects/Certificate_Type__c.object
<CustomObject>
    <description>Selection of job certificate types
Connects to the HTML page in - Setup, App Setup, Develop, Pages</description>
    <label>Certificate Type</label>
    <nameField>
        <label>Certificate Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificate Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ENSProduct__c.object
<CustomObject>
    <description>Contains all the products available for selection on the Job Item object</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Australian</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>eLearning</fullName>
                </value>
                <value>
                    <fullName>English language books</fullName>
                </value>
                <value>
                    <fullName>Foreign language books</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>NIP Flat</fullName>
                </value>
                <value>
                    <fullName>NIP 360</fullName>
                </value>
                <value>
                    <fullName>Tailored Case Studies</fullName>
                </value>
                <value>
                    <fullName>Training Day</fullName>
                </value>
                <value>
                    <fullName>Additional Day</fullName>
                </value>
                <value>
                    <fullName>Manual: 250 Page</fullName>
                </value>
                <value>
                    <fullName>Workbook: 96 Page</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>eLearning</fullName>
                </value>
                <value>
                    <fullName>Leaders Guide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ENSProduct</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ENSProducts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Item__c.object
<CustomObject>
    <description>Records the deliverables for each job. The job items should match the pricing sheet</description>
    <fields>
        <fullName>ENSProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ENSProduct</label>
        <referenceTo>ENSProduct__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>R00N20000001UZTxEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>CASE (Job__r.Job_Type__c
            ,&quot;Consulting&quot;,&quot;Consulting&quot;
            ,&quot;Retainer&quot;,&quot;Consulting&quot;
            ,&quot;Training&quot;,&quot;Training&quot;
            ,&quot;OTHER&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_FX__c</fullName>
        <inlineHelpText>Service - Enter the DAILY rate
Materials - Enter ITEM Price</inlineHelpText>
        <label>Price FX</label>
        <precision>12</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Service - enter number of DAYS
Materials - enter number of ITEMS
For in house trainer jobs, add the prof fee quantity as 0</inlineHelpText>
        <label>Quantity</label>
        <precision>11</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <description>[Address Michael&apos;s issue of wanting to add multiple days of work in one record. This creates no problem apart from reporting granularity]</description>
        <inlineHelpText>The date that the service was performed.</inlineHelpText>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Item</label>
    <nameField>
        <displayFormat>JI-{000000}</displayFormat>
        <label>Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Items</pluralLabel>
    <recordTypes>
        <fullName>Material</fullName>
        <active>true</active>
        <description>Physical merchandise sold by ENS International, such as books.</description>
        <label>Material</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>Job__r.Job_Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Materials_Share__c</fullName>
        <inlineHelpText>Enter 80% for ENS role
Enter appropriate % for Sell role (eg 20% if 1 seller, 10% each if 2 sellers, etc)</inlineHelpText>
        <label>Materials Share %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prof_Serv_Share__c</fullName>
        <label>Prof Serv Share %</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <formula>Job__r.Job_First_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <recordTypes>
        <fullName>Presenter</fullName>
        <active>true</active>
        <description>Includes Job Items as a related list.</description>
        <label>Presenter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Customers who participated in the course or training package.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>case( Job__r.Job_Type__c ,
          &quot;Consulting&quot;, &quot;Consulting&quot;, 
          &quot;Training&quot;,&quot;Training&quot;, 
          &quot;Retainer&quot;,&quot;Retainer&quot;, 
           &quot;Coaching&quot;,&quot;Coaching&quot;, 
            &quot;ERROR&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <formula>Job__r.Job_First_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCertificate.cls
public class TestCertificate {
    public static testMethod void testCertificate() {
      PageReference pageRef = new PageReference('Page.certificate');
      Test.setCurrentPage(pageRef);
      
      //build the needed objects
        recordtype[] RT = [Select  r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Job_Role__c' order by r.Name ASC];
        Account acc = new Account(name='testCertificate');
        insert acc;
        Contact con = new Contact(AccountId = acc.id, FirstName = 'Fname1', LastName = 'Lname1');
        insert con;
        Contact con2 = new Contact(AccountId = acc.id, FirstName = 'Fname2', LastName = 'Lname2');
        insert con2;
        ENSProduct__c prod1 = new ENSProduct__c(Name = 'test Material 1', Category__c = 'Materials', Type__c = 'Manual: 250 Page');
        insert prod1;
        ENSProduct__c prod2 = new ENSProduct__c(Name = 'test Training 1', Category__c = 'Training', Type__c = 'Training Day');
        insert prod2;
        Date myDate = Date.newInstance(2008,6,1);
        Datetime myDatetime = Datetime.newInstance(2008,6,10,8,30,0);
        Certificate_Type__c c1 = new Certificate_Type__c(First_Para_Text__c = 'test', Second_Para_Text__c = 'test', Third_Para_Text__c = 'test');
        insert c1;
        Job__c job = new Job__c(Job_Type__c = 'Standard', Account__c = acc.id, Certificate_Type__c = c1.id, Program_Duration__c = 'test', Certificate_Date_Text__c = 'test', Venue_Name__c = 'test', Venue_City__c = 'testcity', Venue_Country__c = 'Test', Proposal_Date__c = date.today());
        insert job;
        
        Job_Role__c role1 = new Job_Role__c(Job__c = job.id, RecordTypeId = RT[0].Id, Role__c = 'ENS', Prof_Serv_Share__c = 10, Materials_Share__c = 10);
        insert role1; 
        Job_Role__c role2 = new Job_Role__c(Job__c = job.id, RecordTypeId = RT[1].Id, Role__c = 'Presenter', Contact__c = con.id);
        insert role2; 
        Job_Role__c role3 = new Job_Role__c(Job__c = job.id, RecordTypeId = RT[1].Id, Role__c = 'Presenter', Contact__c = con2.id);
        insert role3;
        
        //create
        Job_Item__c Item1 = new Job_Item__c(Job__c = job.id, Price_FX__c = 200.00, Quantity__c = 5, ENSProduct__c = prod1.id);
        insert Item1;
        Job_Item__c Item2 = new Job_Item__c(Job__c = job.id, Job_Role__c = role2.id, Price_FX__c = 5000.00, ENSProduct__c = prod2.id, Work_Start_Date__c = myDate);
        insert Item2;
        Participant__c p1 = new Participant__c(Job__c = job.id, Contact__c = con.id);
        insert p1;
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', Job.Id);
        Certificate controller = new Certificate();
        controller.getCtext();
        controller.getParticipants();
        controller.getJob();
    }
}