objects/ENSProduct__c.object
<CustomObject>
    <description>Contains all the products available for selection on the Job Item object</description>
    <label>ENSProduct</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ENSProducts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Item__c.object
<CustomObject>
    <description>Records the deliverables for each job. The job items should match the pricing sheet</description>
    <fields>
        <fullName>ENSProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ENSProduct</label>
        <referenceTo>ENSProduct__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>R00N20000001UZTxEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Value_AUD__c</fullName>
        <formula>Item_Value_FX__c  /  Job_Billing_X_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Value AUD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Value_FX__c</fullName>
        <formula>Price_FX__c * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Value FX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_FX__c</fullName>
        <inlineHelpText>Service - Enter the DAILY rate
Materials - Enter ITEM Price</inlineHelpText>
        <label>Price FX</label>
        <precision>12</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Service - enter number of DAYS
Materials - enter number of ITEMS
For in house trainer jobs, add the prof fee quantity as 0</inlineHelpText>
        <label>Quantity</label>
        <precision>11</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <description>[Address Michael&apos;s issue of wanting to add multiple days of work in one record. This creates no problem apart from reporting granularity]</description>
        <inlineHelpText>The date that the service was performed.</inlineHelpText>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Item</label>
    <nameField>
        <displayFormat>JI-{000000}</displayFormat>
        <label>Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Items</pluralLabel>
    <recordTypes>
        <fullName>Material</fullName>
        <active>true</active>
        <description>Physical merchandise sold by ENS International, such as books.</description>
        <label>Material</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_FX_Materials_Total__c</fullName>
        <formula>Job__r.FX_Materials_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job FX Materials Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_FX_Prof_Serv_Total__c</fullName>
        <formula>Job__r.FX_Prof_Serv_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job FX Prof Serv Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Materials_Share_AUD_Total__c</fullName>
        <formula>IF (Job__r.Billing_X_Rate__c =0,0,  Materials_Share_FX_Total__c   /  Job__r.Billing_X_Rate__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Materials Share AUD Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Materials_Share_FX_Total__c</fullName>
        <formula>Job_FX_Materials_Total__c * Materials_Share__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Materials Share FX Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Materials_Share__c</fullName>
        <inlineHelpText>Enter 80% for ENS role
Enter appropriate % for Sell role (eg 20% if 1 seller, 10% each if 2 sellers, etc)</inlineHelpText>
        <label>Materials Share %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prof_Serv_Share_AUD__c</fullName>
        <formula>IF (Job__r.Billing_X_Rate__c =0,0, Prof_Serv_Share_FX_Total__c  /  Job__r.Billing_X_Rate__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prof Serv Share AUD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prof_Serv_Share_FX_Total__c</fullName>
        <formula>if( $RecordType.Name = &quot;Presenter&quot;,
    Presenter_Fee__c ,   
    Job_FX_Prof_Serv_Total__c * Prof_Serv_Share__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prof Serv Share FX Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prof_Serv_Share__c</fullName>
        <label>Prof Serv Share %</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <formula>Job__r.Job_First_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Customers who participated in the course or training package.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <formula>Job__r.Job_First_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JobExt.cls
public class JobExt {
    /*
      Brief Sheet Extender Class, displays brief sheet fields
      in a PDF page
    */

    // Initialise variables
    String Id;
    public Decimal Total = 0.00;
    public Decimal Total_AUD = 0.00;
    public Decimal GTotal = 0.00;
    public Decimal GTotal_AUD = 0.00;
    Public Decimal Materials_Total=0.00;
    Public String Materials_Total_AUD;
    
    // Grab ID from query string and store
    public JobExt(ApexPages.StandardController controller) {
      Id = ApexPages.currentPage().getParameters().get('Id');
    }
    
    public Decimal getMaterials_Total(){
      return Materials_Total;
    }
    
   public String getMaterials_Total_AUD(){
      return Materials_Total_AUD;
    }
    
    // Return all Job Roles pertaining to this Job
    public List<Job_Role__c> getJR(){
      return [select Role__c, Contact__r.FirstName, Prof_Serv_Share__c, Contact__r.LastName,Job_FX_Prof_Serv_Total__c, Prof_Serv_Share_FX_Total__c, Materials_Share__c,Materials_Share_FX_Total__c, Materials_Share_AUD_Total__c, Prof_Serv_Share_AUD__c, Job_FX_Materials_Total__c from Job_Role__c where Job__c =:Id];
    }
    
    // Return all Job Items pertaining to this Job
    public List<Job_Item__c> getJI(){
      return [select Work_Start_Date__c, Quantity__c, ENSProduct__r.Name, Price_FX__c, RecordType.Name, Item_Value_FX__c, Item_Value_AUD__c from Job_Item__c where RecordType.Name = 'Material' and Job__c =:Id];
    }
    
    // Return list of participants
    //public Integer getParticipants(){
      //return [select count() from Participant__c where Job__c =: Id];
    //}
    
    // Calculate temporary Totals to use for Brief sheet display
    // this is done on tmp fields on the Job to display currency formatting correctly
    public PageReference Totals(){
    	Decimal MTAUD=0.00;
      for(Job_Role__c thisJR:getJR()){
        Total += thisJR.Prof_Serv_Share_FX_Total__c;
        Total_AUD += thisJR.Prof_Serv_Share_AUD__c;
        Materials_Total+=thisJR.Materials_Share_FX_Total__c;
        MTAUD+=thisJR.Materials_Share_AUD_Total__c;
      }
      Materials_Total_AUD ='$'+string.valueOf(MTAUD);
      for(Job_Item__c thisJI:getJI()){
        GTotal += thisJI.Item_Value_FX__c;
        GTotal_AUD += thisJI.Item_Value_AUD__c;
      }
      Job__c thisJob = new Job__c(Id = Id, tmp_Total__c = Total, tmp_Total_AUD__c = Total_AUD, tmp_GTotal__c = GTotal, tmp_GTotal_AUD__c = GTotal_AUD);
      update thisJob;
      return null; 
    }
}