objects/ENSProduct__c.object
<CustomObject>
    <description>Contains all the products available for selection on the Job Item object</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Australian</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>eLearning</fullName>
                </value>
                <value>
                    <fullName>English language books</fullName>
                </value>
                <value>
                    <fullName>Foreign language books</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>NIP Flat</fullName>
                </value>
                <value>
                    <fullName>NIP 360</fullName>
                </value>
                <value>
                    <fullName>Tailored Case Studies</fullName>
                </value>
                <value>
                    <fullName>Training Day</fullName>
                </value>
                <value>
                    <fullName>Additional Day</fullName>
                </value>
                <value>
                    <fullName>Manual: 250 Page</fullName>
                </value>
                <value>
                    <fullName>Workbook: 96 Page</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>eLearning</fullName>
                </value>
                <value>
                    <fullName>Leaders Guide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ENSProduct</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ENSProducts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Item__c.object
<CustomObject>
    <description>Records the deliverables for each job. The job items should match the pricing sheet</description>
    <fields>
        <fullName>ENSProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ENSProduct</label>
        <referenceTo>ENSProduct__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>R00N20000001UZTxEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>CASE (Job__r.Job_Type__c
            ,&quot;Consulting&quot;,&quot;Consulting&quot;
            ,&quot;Retainer&quot;,&quot;Consulting&quot;
            ,&quot;Training&quot;,&quot;Training&quot;
            ,&quot;OTHER&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_FX__c</fullName>
        <inlineHelpText>Service - Enter the DAILY rate
Materials - Enter ITEM Price</inlineHelpText>
        <label>Price FX</label>
        <precision>12</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Service - enter number of DAYS
Materials - enter number of ITEMS
For in house trainer jobs, add the prof fee quantity as 0</inlineHelpText>
        <label>Quantity</label>
        <precision>11</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <label>Job Item</label>
    <nameField>
        <displayFormat>JI-{000000}</displayFormat>
        <label>Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Items</pluralLabel>
    <recordTypes>
        <fullName>Material</fullName>
        <active>true</active>
        <description>Physical merchandise sold by ENS International, such as books.</description>
        <label>Material</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>Job__r.Job_Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Materials_Share__c</fullName>
        <inlineHelpText>Enter 80% for ENS role
Enter appropriate % for Sell role (eg 20% if 1 seller, 10% each if 2 sellers, etc)</inlineHelpText>
        <label>Materials Share %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prof_Serv_Share__c</fullName>
        <label>Prof Serv Share %</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Customers who participated in the course or training package.</description>
    <fields>
        <fullName>Certificate_Status__c</fullName>
        <label>Certificate Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awarded</fullName>
                    <default>true</default>
                    <label>Awarded</label>
                </value>
                <value>
                    <fullName>Withheld</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>case( Job__r.Job_Type__c ,
          &quot;Consulting&quot;, &quot;Consulting&quot;, 
          &quot;Training&quot;,&quot;Training&quot;, 
          &quot;Retainer&quot;,&quot;Retainer&quot;, 
           &quot;Coaching&quot;,&quot;Coaching&quot;, 
            &quot;ERROR&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPortalSharing_JobRoleAction.cls
@isTest
public class TestPortalSharing_JobRoleAction {
  
    static testMethod void myUnitTest() {
        try {

            //Test Insert Job Role

            //Build the needed records
            recordtype[] RT = [Select r.Id, r.SobjectType, r.Name From RecordType r where sobjecttype ='Job_Role__c' order by r.Name ASC];
            
            //Build Account + Contact
            Account testAcc = new Account(name='testPortalSharingAcc');
            Insert testAcc;

            Contact testCon = new Contact(AccountId = testAcc.id, FirstName = 'Fname1', LastName = 'Lname1');
            Insert testCon;
            
            //Partner Record - profile id: 00ew0000001mtcN for production, 00e7E000000Lqfa for sandbox
            User testPartnerUser = new User(FirstName = 'Partner', LastName = 'User1', Email = 'partnerexample123@example.com', Username = 'partnerexample123@example.com', Alias = 'PetrCech', ProfileId = '00ew0000001mtcN', TimeZoneSidKey = 'America/Denver', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', ContactId = testCon.id, IsActive = TRUE);
            insert testPartnerUser;

            //Build Job and related info
            Job__c testJob = new Job__c(Job_Type__c = 'Standard', Account__c = testAcc.id, Program_Duration__c = 'test', Venue_Name__c = 'test', Venue_City__c = 'testcity', Venue_Country__c = 'TestCountry');
            Insert testJob;
    
            ENSProduct__c testENSProd = new ENSProduct__c(Name = 'test Material 1', Category__c = 'Materials', Type__c = 'Manual: 250 Page');
            insert testENSProd;

            Job_Item__c testJobItem = new Job_Item__c(Job__c = testJob.id, Price_FX__c = 200.00, Quantity__c = 5, ENSProduct__c = testENSProd.id);
            insert testJobItem;        

            Participant__c testParticipant = new Participant__c(Job__c = testJob.id, Contact__c = testCon.id, Certificate_Status__c = 'Awarded');
            insert testParticipant;

            //Build job role = Sell - trigger PortalSharingJobRoleAction(IsInsert)
            Job_Role__c testJobRole = new Job_Role__c(Job__c = testJob.id, Contact__c = testCon.id, RecordTypeId = RT[0].Id, Role__c = 'SELL', Prof_Serv_Share__c = 10, Materials_Share__c = 10);
            insert testJobRole;
 

            //Test Delete Job Role
            Job_Role__c testJobRoleDel = [SELECT id FROM Job_Role__c WHERE id =: testJobRole.id];
            delete testJobRoleDel;

        } 
        catch (DmlException e) {
            //System.assert(false);
        }    
    }
}