objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Customers who participated in the course or training package.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDeleteParticipants.cls
public class TestDeleteParticipants {
    public static testMethod void testDeleteParticipants() { 
    	
    	//Job__c aJob=new Job__c();
    	//Contact__c aContact=new Contact__c();
        //List<Participant__c> aPartList = [select id from Participant__c where job__c <> null and Contact__r.Last_Job_ID__c<> null limit 1 ];
        Participant__c aPartList = [select id from Participant__c where job__c <> null and Contact__r.Last_Job_ID__c<> null limit 1 ];
        delete aPartList;
        
         
    	
    }
}