objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <recordTypes>
        <fullName>Presenter</fullName>
        <active>true</active>
        <description>Includes Job Items as a related list.</description>
        <label>Presenter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Customers who participated in the course or training package.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_First_Date__c</fullName>
        <formula>Job__r.Job_First_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job First Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Last_Date__c</fullName>
        <formula>Job__r.Job_Last_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Public_Program_Name__c</fullName>
        <formula>case(Job__r.Public_Program_Name__c , 
&quot;Developing Effective Negotiation Skills&quot;, 
&quot;Developing Effective Negotiation Skills&quot;, 

&quot;Professional Negotiation and Influencing&quot;,
&quot;Professional Negotiation and Influencing&quot;, 

&quot;Advanced Negotiation and Influencing&quot;,
&quot;Advanced Negotiation and Influencing&quot;, 

&quot;Level 1 - Professional Negotiation&quot;,
&quot;Level 1 - Professional Negotiation&quot;,

&quot;Professional Negotiation - Level 1&quot;,
&quot;Professional Negotiation - Level 1&quot;,

&quot;Level 2 - Strategic Negotiation&quot;,
&quot;Level 2 - Strategic Negotiation&quot;,

&quot;Strategic Negotiation - Level 2&quot;,
&quot;Strategic Negotiation - Level 2&quot;,

&quot;Level 3 - Expert Negotiation&quot;,
&quot;Level 3 - Expert Negotiation&quot;,

&quot;Expert Negotiation - Level 3&quot;,
&quot;Expert Negotiation - Level 3&quot;,

&quot;Professional &amp; Strategic Negotiation&quot;,
&quot;Professional &amp; Strategic Negotiation&quot;,

&quot;Dynamics of Negotiation and Influencing:Feedback &amp; Finetuning&quot;,
&quot;Dynamics of Negotiation and Influencing:Feedback &amp; Finetuning&quot;,

&quot;Negotiating and Influencing Skills&quot;,
&quot;Negotiating and Influencing Skills&quot;,

&quot;Advanced Negotiator&quot;,
&quot;Advanced Negotiator&quot;,

&quot;Dynamics of Negotiation and Influencing&quot;,
&quot;Dynamics of Negotiation and Influencing&quot;,

&quot;Refresher&quot;,
&quot;Refresher&quot;,

&quot;Verhandlungsführung mit System: Grenzen explorieren, Neues ausprobieren&quot;,
&quot;Verhandlungsführung mit System: Grenzen explorieren, Neues ausprobieren&quot;,

&quot;Negotiation Fundamentals&quot;,
&quot;Negotiation Fundamentals&quot;,

&quot;Negotiation Preparation&quot;,
&quot;Negotiation Preparation&quot;,

&quot;Negotiation Tactics&quot;,
&quot;Negotiation Tactics&quot;,

&quot;Concessions &amp; Deadlocks&quot;,
&quot;Concessions &amp; Deadlocks&quot;,

&quot;Stakeholder Engagement&quot;,
&quot;Stakeholder Engagement&quot;,

&quot;null&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Public Program Name</label>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <recordTypes>
        <fullName>PAX</fullName>
        <active>true</active>
        <description>Records for PAX after the 2018 refresh</description>
        <label>PAX</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/paxHistoryController.cls
public class paxHistoryController {
    
    public paxHistoryController(ApexPages.StandardController stdController) {
    }
    
    //public static map<Job__c, Job_Role__c> jobMap {get;set;}
    
    public static map<Job__c, Job_Role__c> getjobMap() {
        
        map<Job__c, Job_Role__c> myMap = new map<Job__c, Job_Role__c>();
        
        Participant__c pax = [SELECT Id, Contact__c 
                              FROM Participant__c
                              WHERE Id = :apexPages.currentPage().getParameters().get('id')
                              LIMIT 1
                             ];
        
        for(Participant__c p : [SELECT Id, Job__c, Job__r.Name, Job__r.Job_First_Date__c, Job__r.Job_Last_Date__c 
                                FROM Participant__c 
                                WHERE Contact__c = :pax.Contact__c 
                                AND Id != :pax.Id 
                                order by Job__r.Job_First_Date__c DESC NULLS LAST]){
                                    
                                    Job__c[] job = [SELECT Id, Name, Job_First_Date__c, Job_Last_Date__c, Public_Program_Name__c, Certificate_Date_Text__c, Comments__c
                                                    FROM Job__c 
                                                    WHERE Id = :p.Job__c
                                                    LIMIT 1]; 
                                    
                                    Job_Role__c[] presenter = [SELECT Id, Contact__r.FirstName, Contact__r.LastName
                                                               FROM Job_Role__c 
                                                               WHERE Job__c = :p.Job__c
                                                               AND Role__c = 'Presenter' limit 1];
                                    
                                    
                                    if(presenter.size() != 0){
                                        myMap.put(job[0], presenter[0]);
                                    }
                                    
                                }
        
        return myMap;
        
    }
    
}