objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Item__c.object
<CustomObject>
    <description>Records the deliverables for each job. The job items should match the pricing sheet</description>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Item</label>
    <nameField>
        <displayFormat>JI-{000000}</displayFormat>
        <label>Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <recordTypes>
        <fullName>Presenter</fullName>
        <active>true</active>
        <description>Includes Job Items as a related list.</description>
        <label>Presenter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reporting_Job_Item__c.object
<CustomObject>
    <description>A read only object used purely for reporting purposes, with data populated via Apex tirggers.</description>
    <fields>
        <fullName>Job_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Item</label>
        <referenceTo>Job_Item__c</referenceTo>
        <relationshipLabel>Reporting Job Items</relationshipLabel>
        <relationshipName>R00N20000001X4W4EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Reporting Job Items</relationshipLabel>
        <relationshipName>R00N20000001X4W8EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Reporting Job Items</relationshipLabel>
        <relationshipName>ReportingJobItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>case(Job_Role__r.Role__c,
&quot;Presenter&quot;,&quot;Presenter&quot;,
&quot;ENS&quot;,&quot;ENS&quot;,
&quot;Spot&quot;,&quot;Spot&quot;,
&quot;Sell&quot;,&quot;Sell&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <label>Reporting Job Item</label>
    <nameField>
        <displayFormat>RJI-{00000000}</displayFormat>
        <label>Reporting Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GenReportingJobItems.cls
public class GenReportingJobItems {
    /* Generates Reporting Job Item Records for every Job_Item and Job_Role that gets
       added deleted or updated 
    */
    
    public static void genJobItem(Job_Item__c[] newJobItems) {
        // Create Blank list of Reporting Job Items
        List<Reporting_Job_Item__c> Report = new List<Reporting_Job_Item__c>();
        Set<String> UniqueJobIds = new Set<String>();   
        // Get list of Unique "Jobs" within the Batch of Job Items
        for (Job_Item__c thisJobItem: newJobItems) {
          if(UniqueJobIds.contains(thisJobItem.Job__c)){continue;}
          else{UniqueJobIds.add(thisJobItem.Job__c);}
        }
        // Query any previous reports for these job items and delete them to start fresh each time
        List<Reporting_Job_Item__c> prevReports= [select Id, Job_Item__c, Job_Role__c from Reporting_Job_Item__c where Job_Item__c in :newJobItems];
                       if (prevReports.size()>0) {
                delete prevReports; 
                }
        
        // Query Job Roles related to Unique Jobs
        List<Job_Role__c> Roles = [select Id, Role__c, RecordType.Name, Job__c from Job_Role__c where Job__c  in :UniqueJobIds];
        //system.debug(Roles.size());
        // Copy of Job Items list (apex seems to get confused when using the existing batch list)
        //List<Job_Item__c> Job_Items = [select Id, RecordType.Name, Job_Role__c, Job__c from Job_Item__c where Id in :newJobItems];
        //system.debug('new job items szie: '+newJobItems.size());
        
        //Jack added on 21/01/2010 
        //to fix the Null recordtype name problem
        RecordType PresenterRT=[select id from recordtype where name='Presenter'];
        //Jack added ends on 21/01/2010
        
        
        
        // Loop Through Job Roles and Job Items Joining them up as we go in a Reporting Job Item Object
        for(Job_Item__c JI: newJobItems){
            //system.debug('JI.Job_Role__c: '+JI.Job_Role__c);
            
            for(Job_Role__c JR: Roles){
              System.debug('JR.RecordType.Name:'+JR.RecordType.Name);
              System.debug('JR.RecordTypeId:'+JR.RecordTypeId);
              
              /*
              //Jack disabled following code on 21/01/2010
              if(JR.RecordType.Name == 'Presenter' && JR.Id == JI.Job_Role__c){
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JI.Job_Role__c));
              }
              else if(JR.RecordType.Name != 'Presenter' && JR.Job__c == JI.Job__c){
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JR.Id));
              }
              //Jack disabled ends on 21/01/2010
              */
              
              //Jack added on 21/01/2010 
              if(JR.RecordTypeId == PresenterRT.id && JR.Id == JI.Job_Role__c){
              	system.debug('JR.RecordTypeId == PresenterRT is '+(JR.RecordTypeId == PresenterRT.id));
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JI.Job_Role__c));
              }
              else if(JR.RecordTypeId != PresenterRT.id && JR.Job__c == JI.Job__c){
              	system.debug('JR.RecordTypeId != PresenterRT is '+(JR.RecordTypeId != PresenterRT.id));
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JR.Id));
              }
              //Jack added ends on 21/01/2010
            }
        }
 //system.debug('Report szie: '+Report.size());
                insert Report;          
    }
    
    public static void genJobRole(Job_Role__c[] newJobRoles) {
    	system.debug('Start debug*********************************');
        if(JobAction.IsUpdateJobRoleNeeded==true){
            // Create Blank list of Reporting Job Items
        List<Reporting_Job_Item__c> Report = new List<Reporting_Job_Item__c>();
        Set<String> UniqueJobIds = new Set<String>();   
        // Get list of Unique "Jobs" within the Batch of Job Items
        for (Job_Role__c thisJobRole: newJobRoles) {
          if(UniqueJobIds.contains(thisJobRole.Job__c)){continue;}
          else{UniqueJobIds.add(thisJobRole.Job__c);}
        }
        // Query any previous reports for these job items and delete them to start fresh each time
        // Jack disabled on 26/02/2009
        //List<Reporting_Job_Item__c> prevReports= [select Id, Job_Item__c, Job_Role__c from Reporting_Job_Item__c where Job_Role__c in :newJobRoles];
        //Jack ends
        //Jack added on 26/02/2009

        List<Reporting_Job_Item__c> prevReports= [select Id, Job_Item__c, Job_Role__c from Reporting_Job_Item__c where Job_Role__c in :newJobRoles];
        //Jack ends
       
                if (prevReports.size()>0) {
                    // System.debug('prevReports.size():'+prevReports.size());
           // System.debug('Job_Role__c:'+prevReports[0].Job_Role__c);
                //System.debug('Job_Item__c:'+prevReports[0].Job_Item__c);
                //System.debug('***************');

                delete prevReports;   
                }
        
        
        // Copy of Job Roles list (apex seems to get confused when using the existing batch list)
        //List<Job_Role__c> Roles = [select Id, Role__c, RecordType.Name, Job__c from Job_Role__c where Id in :newJobRoles];
        //system.debug(Roles.size());
        // Query Job Items related to unique Jobs
        List<Job_Item__c> Job_Items = [select Id, RecordType.Name, RecordTypeId,Job_Role__c, Job__c from Job_Item__c where Job__c in :UniqueJobIds];
        system.debug('newJobRoles.size:'+newJobRoles.size());
        
        //Jack added on 21/01/2010 
        //to fix the Null recordtype name problem
        RecordType PresenterRT=[select id from recordtype where name='Presenter'];
        //Jack added ends on 21/01/2010
        
        // Loop Through Job Roles and Job Items Joining them up as we go in a Reporting Job Item Object
        for(Job_Role__c JR: newJobRoles){
           for(Job_Item__c JI: Job_Items){
            System.debug('JR.RecordType.Name:'+JR.RecordType.Name);
            System.debug('JR.RecordTypeId:'+JR.RecordTypeId);
            
            /*
              //Jack disabled following code on 21/01/2010
              if(JR.RecordType.Name == 'Presenter' && JR.Id == JI.Job_Role__c){
                System.debug('Presenter, Job_Role__c:'+JR.Id);
                System.debug('Presenter, Job_Job__c:'+JI.Job__c);
                System.debug('Presenter, Job_Item__c:'+JI.Id);
                System.debug('***************');
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JI.Job_Role__c));
              }
              else if(JR.RecordType.Name != 'Presenter' && JR.Job__c == JI.Job__c){
                System.debug('Non-Presenter, Job_Role__c:'+JR.Id);
                System.debug('Non-Presenter, Job_Job__c:'+JI.Job__c);
                System.debug('Non-Presenter, Job_Item__c:'+JI.Id);
                System.debug('***************');
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JR.Id));
              }
              //Jack disabled ends on 21/01/2010
              */
              
              //Jack added on 21/01/2010 
              if(JR.RecordTypeId == PresenterRT.id && JR.Id == JI.Job_Role__c){
              	system.debug('JR.RecordTypeId == PresenterRT is '+(JR.RecordTypeId == PresenterRT.id));
              	System.debug('Presenter, Job_Role__c:'+JR.Id);
                System.debug('Presenter, Job_Job__c:'+JI.Job__c);
                System.debug('Presenter, Job_Item__c:'+JI.Id);
                System.debug('***************');
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JI.Job_Role__c));
              }
              else if(JR.RecordTypeId != PresenterRT.id && JR.Job__c == JI.Job__c){
              	system.debug('JR.RecordTypeId != PresenterRT is '+(JR.RecordTypeId != PresenterRT.id));
              	System.debug('Non-Presenter, Job_Role__c:'+JR.Id);
                System.debug('Non-Presenter, Job_Job__c:'+JI.Job__c);
                System.debug('Non-Presenter, Job_Item__c:'+JI.Id);
                System.debug('***************');
                Report.add(new Reporting_Job_Item__c(Job__c = JI.Job__c, Job_Item__c = JI.Id, Job_Role__c = JR.Id));
              }
              //Jack added ends on 21/01/2010
            }
        }
        insert Report;
        }
        
    }
}