objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Materials_Share__c</fullName>
        <inlineHelpText>Enter 80% for ENS role
Enter appropriate % for Sell role (eg 20% if 1 seller, 10% each if 2 sellers, etc)</inlineHelpText>
        <label>Materials Share %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prof_Serv_Share__c</fullName>
        <label>Prof Serv Share %</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <recordTypes>
        <fullName>Presenter</fullName>
        <active>true</active>
        <description>Includes Job Items as a related list.</description>
        <label>Presenter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Customers who participated in the course or training package.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testEmailToXXX.cls
@isTest
public class testEmailToXXX {
    
    public static string jobId {get;}
    public static Job__c job {get;}
    
    public static void initData(){
        
        //insert account
        Account a = new Account(Name = 'Test Account');
        insert a;
        system.debug('Account Inserted');

        //insert contacts
        //(participant; spot; sell; presenter; NAM; Admin)
        Contact c = new Contact(LastName = 'TESTER', Email='test@test.com', AccountId = a.id);
        insert c;
        system.debug('Contact Inserted');
        
        //insert job
        Job__c j = new Job__c(Account__c = a.id, NAM_Name__c = c.id, Admin_Contact__c = c.Id);
        insert j;
        system.debug('Job Inserted');
        
        job = j;
        jobId = j.id;
        system.debug('Job ID: '+ j.id);
        
        c.Last_Job_ID__c = j.id;
        update c;
        
        //insert participants
    Participant__c p = new Participant__c(Job__c = j.id, Contact__c = c.id);
    insert p;        
        system.debug('Participant Inserted');

        //insert job roles
        Job_Role__c spot = new Job_Role__c(Job__c = j.id, Contact__c = c.id, Role__c = 'Spot', Prof_Serv_Share__c = 5, Materials_Share__c = 5);
        Job_Role__c sell = new Job_Role__c(Job__c = j.id, Contact__c = c.id, Role__c = 'Sell', Prof_Serv_Share__c = 5, Materials_Share__c = 5);
        Job_Role__c pres = new Job_Role__c(Job__c = j.id, Contact__c = c.id, Role__c = 'Presenter', Prof_Serv_Share__c = 5, Materials_Share__c = 5);
        
        insert spot;
        insert sell;
        insert pres;
        system.debug('Job Roles Inserted');

    }

    public static testmethod void testEmailToPax(){
        
        initData();
        
        PageReference paxPageRef = new PageReference('Page.MultiUserEmailToPax');
        
        test.setCurrentPage(paxPageRef); 
        ApexPages.currentPage().getParameters().put('Id', jobId);
        
        ApexPages.StandardController ctrl = new ApexPages.StandardController(job);
        
        MultiUserEmailToPax aGen = new MultiUserEmailToPax(ctrl);
        
        system.runAs([select Id from User where Profile.Name = 'System Administrator' AND isActive = true][0]){
          aGen.UpdateContacts();
        }
    }
    
    public static testmethod void testEmailToPresenter(){
        
        initData();
        
        PageReference paxPageRef = new PageReference('Page.EmailToPresenter');
        
        test.setCurrentPage(paxPageRef); 
        ApexPages.currentPage().getParameters().put('Id', jobId);
        
        ApexPages.StandardController ctrl = new ApexPages.StandardController(job);
        
        EmailToPresenter aGen = new EmailToPresenter(ctrl);
        
        system.runAs([select Id from User where Profile.Name = 'System Administrator' AND isActive = true][0]){
          aGen.UpdateContacts();
        }
        
    }
    
    public static testmethod void testEmailToPresenterSpotSell(){
        
        initData();
        
        PageReference paxPageRef = new PageReference('Page.EmailToPresenterSpotSell');
        
        test.setCurrentPage(paxPageRef); 
        ApexPages.currentPage().getParameters().put('Id', jobId);
        
        ApexPages.StandardController ctrl = new ApexPages.StandardController(job);
        
        EmailToPresenterSpotSell aGen = new EmailToPresenterSpotSell(ctrl);
        
        system.runAs([select Id from User where Profile.Name = 'System Administrator' AND isActive = true][0]){
          aGen.UpdateContacts();
        }
    }
    
    public static testmethod void testEmailToNAMAndAdmin(){
        
        initData();
        
        PageReference paxPageRef = new PageReference('Page.EmailToNAMAndAdminPage');
        
        test.setCurrentPage(paxPageRef); 
        ApexPages.currentPage().getParameters().put('Id', jobId);
        
        ApexPages.StandardController ctrl = new ApexPages.StandardController(job);
        
        EmailToNAMAndAdmin aGen = new EmailToNAMAndAdmin(ctrl);
        
        system.runAs([select Id from User where Profile.Name = 'System Administrator' AND isActive = true][0]){
          aGen.UpdateContacts();
        }
        
    }
    
}