objects/Job__c.object
<CustomObject>
    <customHelp>Job_Help_Text_test</customHelp>
    <description>Contains all ENS assignments (training, consulting and retainers) and Proposals</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Job_Item__c.object
<CustomObject>
    <description>Records the deliverables for each job. The job items should match the pricing sheet</description>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Items</relationshipLabel>
        <relationshipName>JobItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <description>[Address Michael&apos;s issue of wanting to add multiple days of work in one record. This creates no problem apart from reporting granularity]</description>
        <inlineHelpText>The date that the service was performed.</inlineHelpText>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Item</label>
    <nameField>
        <displayFormat>JI-{000000}</displayFormat>
        <label>Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Role__c.object
<CustomObject>
    <description>Records the roles for each job - ENS, Presenter, Spot and Sell</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Job__r.Account__r.Name</formula>
        <label>Job Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>R00N20000001UZYzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <formula>CASE(Role__c , 
&quot;Spot&quot;, &quot;Spot&quot;,
&quot;Sell&quot;, &quot;Sell&quot;,
&quot;ENS&quot;, &quot;ENS&quot;,
&quot;Presenter&quot;, &quot;Presenter&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Roles</relationshipLabel>
        <relationshipName>JobRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENS</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Presenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <formula>Job__r.Job_First_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Role</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Processed_Report__c.object
<CustomObject>
    <label>Processed Report</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Processed Report object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processed Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reporting_Job_Item__c.object
<CustomObject>
    <description>A read only object used purely for reporting purposes, with data populated via Apex tirggers.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>Job_Role__r.Contact__r.FirstName &amp; &quot; &quot; &amp;  Job_Role__r.Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FX_Share_Amount__c</fullName>
        <formula>if( Job_Item_Record_Type__c =&quot;Material&quot;, 
      Job_Role_Materials_Pct__c *  Job_Item__r.Item_Value_FX__c ,
      if(  Role__c =&quot;Presenter&quot;,
              Job_Item__r.Value_Share_Pcnt__c * Job_Item__r.Item_Value_FX__c,

IF ( Job_Item_Record_Type__c =&quot;Fixed Fee&quot;,
0,

IF ( Job_Item_Record_Type__c =&quot;Travel Time&quot;,
0, 

              Job_Role_Prof_Services_Pct__c * Job_Item__r.Item_Value_FX__c)))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FX Share Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Item</label>
        <referenceTo>Job_Item__c</referenceTo>
        <relationshipLabel>Reporting Job Items</relationshipLabel>
        <relationshipName>R00N20000001X4W4EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Role_Contact_ID__c</fullName>
        <formula>Job_Role__r.Contact__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role Contact ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Role_Prof_Services_Pct__c</fullName>
        <formula>Job_Role__r.Prof_Serv_Share__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Role Prof Services %</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Role</label>
        <referenceTo>Job_Role__c</referenceTo>
        <relationshipLabel>Reporting Job Items</relationshipLabel>
        <relationshipName>R00N20000001X4W8EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Reporting Job Items</relationshipLabel>
        <relationshipName>ReportingJobItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <formula>case(Job_Role__r.Role__c,
&quot;Presenter&quot;,&quot;Presenter&quot;,
&quot;ENS&quot;,&quot;ENS&quot;,
&quot;Spot&quot;,&quot;Spot&quot;,
&quot;Sell&quot;,&quot;Sell&quot;,
&quot;ERROR&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Start_Date__c</fullName>
        <description>dates are from the job item</description>
        <formula>IF (  Job_Item_Record_Type__c &lt;&gt; &quot;Material&quot;
      ,Job_Item__r.Work_Start_Date__c
      , Job_Item__r.Job_Work_Start_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>dates are from the job item, For a service the date should be the date of work. For materials the date should be the job first date</inlineHelpText>
        <label>Work_Start_Date</label>
        <type>Date</type>
    </fields>
    <label>Reporting Job Item</label>
    <nameField>
        <displayFormat>RJI-{00000000}</displayFormat>
        <label>Reporting Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LicenseeActivityReport.cls
public class LicenseeActivityReport {
    public List<Reporting_Job_Item__c> Report;
    public List<Job_Role__c> Jobs;
    public integer Proposed = 0;
    public integer Postponed = 0;
    public integer Confirmed = 0;
    
    public Processed_Report__c PR2;
    
    private final Processed_Report__c PR;

    public LicenseeActivityReport(ApexPages.StandardController stdController) {
      // Get Processed Report Record In Question (for a custom object SF.com will only pass an ID)
      this.PR = (Processed_Report__c)stdController.getRecord();   
      // Get Fields of processed report record in question   
      PR2 = [select Contact__c, From_Date__c, To_Date__c FROM Processed_Report__c where Id =: PR.Id];
      
      String ID15digit = String.ValueOf(PR2.Contact__c).SubString(0,15);
      Report = [select Job_Item__r.Work_Start_Date__c, Job_Role__r.Account_Name__c, Job_Role__r.Job__r.Name, Role__c, Job_Role_Prof_Services_Pct__c, FX_Share_Amount__c from Reporting_Job_Item__c WHERE Job_Role_Contact_ID__c =: ID15digit and Job_Item__r.Work_Start_Date__c >=: PR2.From_Date__c and Job_Item__r.Work_Start_Date__c <=: PR2.To_Date__c];
      Jobs = [select job__r.status_new1__c, Contact__r.FirstName, Contact__r.LastName from Job_Role__c where Contact__c =: PR2.Contact__c];
    }    
    
    public String getContact(){
      return Jobs[0].Contact__r.FirstName + ' ' + Jobs[0].Contact__r.LastName;
    }
    
    public List<Reporting_Job_Item__c> getReport(){
      return Report;
    }
    
    public Integer getProposed(){    
      for(Job_Role__c thisJob:Jobs){
        if(thisJob.job__r.status_new1__c == 'Proposed'){Proposed++;}
      }
      return Proposed;
    }
    
    public Integer getPostponed(){
      for(Job_Role__c thisJob:Jobs){
        if(thisJob.job__r.status_new1__c == 'Postponed'){Postponed++;}
      }
      return Postponed;
    }
    
    public Integer getConfirmed(){
      for(Job_Role__c thisJob:Jobs){
        if(thisJob.job__r.status_new1__c == 'Confirmed'){Confirmed++;}
      }
      return Confirmed;
    }
    
}